-- Update design_system_tokens with correct hex values computed from DemoStoke HSL values

-- Update default values for all color columns with correct hex values
ALTER TABLE public.design_system_tokens 
ALTER COLUMN primary_color SET DEFAULT '#00dcf5',
ALTER COLUMN secondary_color SET DEFAULT '#f4d291', 
ALTER COLUMN accent_color SET DEFAULT '#f5f7fa',
ALTER COLUMN success_color SET DEFAULT '#22c55e',
ALTER COLUMN destructive_color SET DEFAULT '#f56565',
ALTER COLUMN warning_color SET DEFAULT '#f59e0b',
ALTER COLUMN background_color SET DEFAULT '#ffffff',
ALTER COLUMN foreground_color SET DEFAULT '#0c1222',
ALTER COLUMN muted_color SET DEFAULT '#f5f7fa',
ALTER COLUMN border_color SET DEFAULT '#e4e9f2',
ALTER COLUMN ring_color SET DEFAULT '#00dcf5',
-- Dark mode colors
ALTER COLUMN primary_color_dark SET DEFAULT '#0da2e7',
ALTER COLUMN secondary_color_dark SET DEFAULT '#d4c29c',
ALTER COLUMN accent_color_dark SET DEFAULT '#2c3e50',
ALTER COLUMN success_color_dark SET DEFAULT '#34d399',
ALTER COLUMN destructive_color_dark SET DEFAULT '#7c2d12',
ALTER COLUMN warning_color_dark SET DEFAULT '#fbbf24',
ALTER COLUMN background_color_dark SET DEFAULT '#0c1222',
ALTER COLUMN foreground_color_dark SET DEFAULT '#f5f7fa',
ALTER COLUMN muted_color_dark SET DEFAULT '#2c3e50',
ALTER COLUMN border_color_dark SET DEFAULT '#2c3e50',
ALTER COLUMN ring_color_dark SET DEFAULT '#4dabf7',
-- Sidebar colors
ALTER COLUMN sidebar_background SET DEFAULT '#fafcfe',
ALTER COLUMN sidebar_foreground SET DEFAULT '#64748b',
ALTER COLUMN sidebar_primary SET DEFAULT '#1a202c',
ALTER COLUMN sidebar_primary_foreground SET DEFAULT '#fafcfe',
ALTER COLUMN sidebar_accent SET DEFAULT '#f8fafc',
ALTER COLUMN sidebar_accent_foreground SET DEFAULT '#1a202c',
ALTER COLUMN sidebar_border SET DEFAULT '#e2e8f0',
ALTER COLUMN sidebar_ring SET DEFAULT '#3b82f6',
-- Dark mode sidebar colors
ALTER COLUMN sidebar_background_dark SET DEFAULT '#1a202c',
ALTER COLUMN sidebar_foreground_dark SET DEFAULT '#f8fafc',
ALTER COLUMN sidebar_primary_dark SET DEFAULT '#4dabf7',
ALTER COLUMN sidebar_primary_foreground_dark SET DEFAULT '#ffffff',
ALTER COLUMN sidebar_accent_dark SET DEFAULT '#374151',
ALTER COLUMN sidebar_accent_foreground_dark SET DEFAULT '#f8fafc',
ALTER COLUMN sidebar_border_dark SET DEFAULT '#374151',
ALTER COLUMN sidebar_ring_dark SET DEFAULT '#3b82f6';

-- Update all existing records with the correct hex values
UPDATE public.design_system_tokens SET
  primary_color = '#00dcf5',
  secondary_color = '#f4d291',
  accent_color = '#f5f7fa',
  success_color = '#22c55e',
  destructive_color = '#f56565',
  warning_color = '#f59e0b',
  background_color = '#ffffff',
  foreground_color = '#0c1222',
  muted_color = '#f5f7fa',
  border_color = '#e4e9f2',
  ring_color = '#00dcf5',
  -- Dark mode colors
  primary_color_dark = '#0da2e7',
  secondary_color_dark = '#d4c29c',
  accent_color_dark = '#2c3e50',
  success_color_dark = '#34d399',
  destructive_color_dark = '#7c2d12',
  warning_color_dark = '#fbbf24',
  background_color_dark = '#0c1222',
  foreground_color_dark = '#f5f7fa',
  muted_color_dark = '#2c3e50',
  border_color_dark = '#2c3e50',
  ring_color_dark = '#4dabf7',
  -- Sidebar colors
  sidebar_background = '#fafcfe',
  sidebar_foreground = '#64748b',
  sidebar_primary = '#1a202c',
  sidebar_primary_foreground = '#fafcfe',
  sidebar_accent = '#f8fafc',
  sidebar_accent_foreground = '#1a202c',
  sidebar_border = '#e2e8f0',
  sidebar_ring = '#3b82f6',
  -- Dark mode sidebar colors
  sidebar_background_dark = '#1a202c',
  sidebar_foreground_dark = '#f8fafc',
  sidebar_primary_dark = '#4dabf7',
  sidebar_primary_foreground_dark = '#ffffff',
  sidebar_accent_dark = '#374151',
  sidebar_accent_foreground_dark = '#f8fafc',
  sidebar_border_dark = '#374151',
  sidebar_ring_dark = '#3b82f6';